version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install
artifacts:
  type: zip
  files:
    - template.json
    - package.json
    - promote.sh
    - promote.yml
    - revert.yml
    - revert.sh
    - index.json
    - lib/**/*
    - src/**/*
